Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using sakuratest.Models;

namespace sakura_test.Controllers
{
    public class LoginController : Controller
    {
        private readonly SalesDbContext _context;

        public LoginController(SalesDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind("UserName", "Password")] User user)
        {
            if(ModelState.IsValid){
                var _user = new SqlParameter("@username", user.UserName.ToLower());
                var _pass = new SqlParameter("@password", user.Password);
                var result = await _context.User.FromSqlRaw(@"Exec dbo.Login_User @username , @password", _user, _pass).ToListAsync();
                int res = result.Count;
                if(res == 0){
                    ModelState.AddModelError("incorrect", "The username or password is incorrect. ");
                }else{
                    var isAdmin = result.Select(x => x.IsAdmin).FirstOrDefault();
                    var user_ = result.Select(x => x.UserName).FirstOrDefault();
                    HttpContext.Session.SetString("isAdmin", isAdmin.ToString().ToLower());
                    HttpContext.Session.SetString("username", user_);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(user);
        }

        [Route("logout")]
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            HttpContext.Session.Remove("isAdmin");
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/OrderListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using sakuratest.Models;

namespace sakura_test.Controllers
{
    public class OrderListController : Controller
    {
        private readonly SalesDbContext _context;

        public OrderListController(SalesDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(OrderList _orderList)
        {
            var _filter_order_no = new SqlParameter("@Filter_OrderNo_", 0);
            var _filter_customer = new SqlParameter("@Filter_Customer_", 0);
            var _orderId = new SqlParameter("@OrderID_", "");
            var _customerId = new SqlParameter("@CustomerID_", "");
            var orderList = await _context.OrderList.FromSqlRaw("Exec dbo.OrderList @Filter_OrderNo_ , @Filter_Customer_, @OrderID_, @CustomerID_", _filter_order_no, _filter_customer, _orderId, _customerId).ToListAsync();
            return View(orderList);
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

@{
    var username = Context.Session.GetString("username");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sakuratest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sakuratest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderList" asp-action="Index">Order List</a>
                        </li>
                    </ul>
                </div>
                @{
                    if (Context.Session.GetString("isAdmin") == "true")
                    {
                        <div class="navbar-collapse collapse w-50 order-3 dual-collapse2">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="#">
                                    Welcome, @username
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div class="navbar-collapse collapse w-50 order-3 dual-collapse2">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                   
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>                                    
                                </li>
                            </ul>
                        </div>
                    }
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - sakuratest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>